/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import con.Jogadas;
import con.JogadoresI;
import javax.swing.JOptionPane;

/**
 *
 * @author igor
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo(String jog1, String jog2) {
        initComponents();
        // this.setBounds(400, 200, 500, 600);
        JogadoresI j = new JogadoresI();
        //  j1.setText(j.getJogador1());
        //   j2.setText(j.getJogador2());
        Jogadores jo = new Jogadores();
        this.setSize(595, 450);
        this.setLocation(400, 200);
        pl1.setText("0");
        pl2.setText("0");
        j1.setText(jog1);
        j2.setText(jog2);
        j1p.setText(j1.getText() + " :");
        j2p.setText(j2.getText() + " :");
        vez.setText(jog1);

        // vez.setText(jog1);
    }

    public void Reiniciar() {
        vez.setText(j1.getText());
        p0.setText("");
        p1.setText("");
        p2.setText("");
        p3.setText("");
        p4.setText("");
        p5.setText("");
        p6.setText("");
        p7.setText("");
        p8.setText("");
      
    }

    public void Velha() {
        if (!p0.getText().equals("") && !p1.getText().equals("") && !p2.getText().equals("") && !p3.getText().equals("") && !p4.getText().equals("") && !p5.getText().equals("") && !p6.getText().equals("") && !p7.getText().equals("") && !p8.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Velha :/");
            Reiniciar();
        }
    }

    private TelaJogo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        vez = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        p0 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        j1p = new javax.swing.JLabel();
        j2p = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pl1 = new javax.swing.JLabel();
        pl2 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 187, 173));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(56, 177, 247));

        jLabel4.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Vez:");

        vez.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        vez.setForeground(new java.awt.Color(254, 254, 254));

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(56, 177, 247));
        jButton2.setText("Ir Para o Início");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(56, 177, 247));
        jButton1.setText("Reiniciar Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        p0.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p0MouseClicked(evt);
            }
        });

        p1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });

        p2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
        });

        p3.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
        });

        p4.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
        });

        p5.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });

        p6.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });

        p7.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7MouseClicked(evt);
            }
        });

        p8.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        p8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotoTexturaMaterial.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        j1p.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        j1p.setForeground(new java.awt.Color(56, 177, 247));

        j2p.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        j2p.setForeground(new java.awt.Color(56, 177, 247));

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 177, 247));
        jLabel2.setText("Placar");

        pl1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        pl1.setForeground(new java.awt.Color(56, 177, 247));

        pl2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        pl2.setForeground(new java.awt.Color(56, 177, 247));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j2p, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pl2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1p, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pl1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2p, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pl2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        j1.setForeground(new java.awt.Color(56, 177, 247));

        j2.setForeground(new java.awt.Color(56, 177, 247));

        jButton4.setBackground(new java.awt.Color(254, 254, 254));
        jButton4.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(56, 177, 247));
        jButton4.setText("Encerrar Desafio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p0MouseClicked
        // TODO add your handling code here:

        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p0.getText().equals("X") || p0.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p0.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p0.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU
        if (!p0.getText().equals("") && !p1.getText().equals("") && !p1.getText().equals("")) {

            if (p0.getText().equals(p1.getText()) && p1.getText().equals(p2.getText())) {

                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();

                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
        if (!p0.getText().equals("") && !p4.getText().equals("") && !p8.getText().equals("")) {
            if (p0.getText().equals(p4.getText()) && p4.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }

            }
        }
        if (!p0.getText().equals("") && !p3.getText().equals("") && !p6.getText().equals("")) {
            if (p0.getText().equals(p3.getText()) && p3.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }


    }//GEN-LAST:event_p0MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p2.getText().equals("X") || p2.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p2.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p2.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU
        if (!p0.getText().equals("") && !p1.getText().equals("") && !p2.getText().equals("")) {

            if (p0.getText().equals(p1.getText()) && p1.getText().equals(p2.getText())) {

                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p2.getText().equals("") && !p5.getText().equals("") && !p8.getText().equals("")) {
            if (p2.getText().equals(p5.getText()) && p5.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
        if (!p2.getText().equals("") && !p4.getText().equals("") && !p6.getText().equals("")) {
            if (p2.getText().equals(p4.getText()) && p4.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

    }//GEN-LAST:event_p2MouseClicked

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p1.getText().equals("X") || p1.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p1.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p1.setText("O");
                vez.setText(j1.getText());
            }

        }
        Velha();
        //----------VERIFICAR SE GANHOU
        if (!p0.getText().equals("") && !p1.getText().equals("") && !p1.getText().equals("")) {

            if (p0.getText().equals(p1.getText()) && p1.getText().equals(p2.getText())) {

                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p1.getText().equals("") && !p4.getText().equals("") && !p7.getText().equals("")) {
            if (p1.getText().equals(p4.getText()) && p4.getText().equals(p7.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }


    }//GEN-LAST:event_p1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Jogadas j = new Jogadas();
        // j.setVez("jogador 1");

        vez.setText(j1.getText());
        p0.setText("");
        p1.setText("");
        p2.setText("");
        p3.setText("");
        p4.setText("");
        p5.setText("");
        p6.setText("");
        p7.setText("");
        p8.setText("");

        // j.setVez("njogou");
        //jLabel5.setText(j.getVez());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p3.getText().equals("X") || p3.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p3.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p3.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p0.getText().equals("") && !p3.getText().equals("") && !p6.getText().equals("")) {
            if (p0.getText().equals(p3.getText()) && p3.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p3.getText().equals("") && !p4.getText().equals("") && !p5.getText().equals("")) {
            if (p3.getText().equals(p4.getText()) && p4.getText().equals(p5.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p4.getText().equals("X") || p4.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p4.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p4.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p0.getText().equals("") && !p4.getText().equals("") && !p8.getText().equals("")) {
            if (p0.getText().equals(p4.getText()) && p4.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }

            }
        }

        if (!p1.getText().equals("") && !p4.getText().equals("") && !p7.getText().equals("")) {
            if (p1.getText().equals(p4.getText()) && p4.getText().equals(p7.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p2.getText().equals("") && !p4.getText().equals("") && !p6.getText().equals("")) {
            if (p2.getText().equals(p4.getText()) && p4.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
        if (!p3.getText().equals("") && !p4.getText().equals("") && !p5.getText().equals("")) {
            if (p3.getText().equals(p4.getText()) && p4.getText().equals(p5.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p5.getText().equals("X") || p5.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p5.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p5.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p2.getText().equals("") && !p5.getText().equals("") && !p8.getText().equals("")) {
            if (p2.getText().equals(p5.getText()) && p5.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p3.getText().equals("") && !p4.getText().equals("") && !p5.getText().equals("")) {
            if (p3.getText().equals(p4.getText()) && p4.getText().equals(p5.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p6.getText().equals("X") || p6.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p6.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p6.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p0.getText().equals("") && !p3.getText().equals("") && !p6.getText().equals("")) {
            if (p0.getText().equals(p3.getText()) && p3.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p2.getText().equals("") && !p4.getText().equals("") && !p6.getText().equals("")) {
            if (p2.getText().equals(p4.getText()) && p4.getText().equals(p6.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
        if (!p6.getText().equals("") && !p7.getText().equals("") && !p8.getText().equals("")) {
            if (p6.getText().equals(p7.getText()) && p7.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p6MouseClicked

    private void p7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p7.getText().equals("X") || p7.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p7.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p7.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p1.getText().equals("") && !p4.getText().equals("") && !p7.getText().equals("")) {
            if (p1.getText().equals(p4.getText()) && p4.getText().equals(p7.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p6.getText().equals("") && !p7.getText().equals("") && !p8.getText().equals("")) {
            if (p6.getText().equals(p7.getText()) && p7.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p7MouseClicked

    private void p8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseClicked
        // TODO add your handling code here:
        if (vez.getText().equals("") || vez.getText().equals("")) {
        } else {
            if (p8.getText().equals("X") || p8.getText().equals("O")) {
                //JOptionPane.showMessageDialog(null, "Este campo ja foi jogado");
            } else if (vez.getText().equals(j1.getText())) {
                p8.setText("X");
                vez.setText(j2.getText());

            } else if (vez.getText().equals(j2.getText())) {
                p8.setText("O");
                vez.setText(j1.getText());

            }
        }
        Velha();
        //----------VERIFICAR SE GANHOU

        if (!p0.getText().equals("") && !p4.getText().equals("") && !p8.getText().equals("")) {
            if (p0.getText().equals(p4.getText()) && p4.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }

            }
        }

        if (!p1.getText().equals("") && !p4.getText().equals("") && !p7.getText().equals("")) {
            if (p1.getText().equals(p4.getText()) && p4.getText().equals(p7.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
        if (!p2.getText().equals("") && !p5.getText().equals("") && !p8.getText().equals("")) {
            if (p2.getText().equals(p5.getText()) && p5.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }

        if (!p6.getText().equals("") && !p7.getText().equals("") && !p8.getText().equals("")) {
            if (p6.getText().equals(p7.getText()) && p7.getText().equals(p8.getText())) {
                if (vez.getText().equals(j1.getText())) {
                    JOptionPane.showMessageDialog(null, j2.getText() + "  venceu!!!");
                    int np2 = 0;
                    np2 = Integer.parseInt(pl2.getText());
                    np2++;
                    pl2.setText(Integer.toString(np2));
                    Reiniciar();
                } else {
                    JOptionPane.showMessageDialog(null, j1.getText() + "  venceu!!!");
                    int np1 = Integer.parseInt(pl1.getText());
                    np1++;
                    pl1.setText(Integer.toString(np1));
                    Reiniciar();
                }
            }
        }
    }//GEN-LAST:event_p8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Jogadores j = new Jogadores();
        this.setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String[] options = {"Sim", "Não"};
        int opc = JOptionPane.showOptionDialog(null, "Deseja encerrar o desafio?", "Encerrar?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (opc == 0) {
            int pf1 = Integer.parseInt(pl1.getText());
            int pf2 = Integer.parseInt(pl2.getText());
            this.setVisible(false);
            Vencedor v = new Vencedor(pf1, pf2, j1.getText(), j2.getText());
            v.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j1p;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j2p;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel p0;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel pl1;
    private javax.swing.JLabel pl2;
    private javax.swing.JLabel vez;
    // End of variables declaration//GEN-END:variables
}
